---
- name: Configure server
  hosts: servers
  vars_files:
    - group_vars/vault.yml
  roles:
    - docker_setup
    - firewall
    - docker_network
    - postgres
    - minio
    - nginx

- name: Deploy application
  hosts: servers
  vars_files:
    - group_vars/vault.yml
  roles:
    - role: docker_deploy
      tags: deploy
